### ISSUE TITLE
Bcon18 Sample code?

### ISSUE THREAD

**Issue by brhumphe** [CGCookie/addon-common#1]
Would it be possible to get the code used in the Bcon18 conference talk? It would be extremely helpful in understanding how to use this framework with a complete working example to work from.

**Comment by vxlcoder** [comment]
Yes!  I will get the code posted as soon as I can.

**Comment by vxlcoder** [comment]
Take a look at the example add-on at https://github.com/CGCookie/ExtruCut.
I will continue to make the example code as clear as possible, adding comments, etc.

When I get more time, I will add more examples.
