### ISSUE TITLE
Can parts of this be used in commercial addon

### ISSUE THREAD

**Issue by JoseConseco** [CGCookie/addon-common#2]
I want to use FSM part of cookiecutter, in my commercial addon. It this allowed?

**Comment by NathanLovato** [comment]
Yes, see the project's license: you can sell your work, but as with every blender add-on, you must also distribute the source code and allow users to freely modify and redistribute your work if they so desire.

**Comment by NathanLovato** [comment]
That's the license Blender itself uses by the way, so the reason you must use the GNU/GPL-v3.0 license is that you use the Blender Python API. Here's a guide to get started with GNU/GPL: https://www.gnu.org/licenses/quick-guide-gplv3.html

**Comment by JoseConseco** [comment]
Yep, my code is also open source, if users want they will be able to modify it. I know I have to use GPL to do addons for blender. I just wanted to make sure it is ok with developer of CookieCutter.

**Comment by NathanLovato** [comment]
You can see the license at the top of most github repositories:

![screenshot from 2019-02-13 16-28-11](https://user-images.githubusercontent.com/12694995/52694270-6cef1900-2fac-11e9-8677-cac43ff7fab9.png)

This is GPL-3, the same as most blender add-ons. So yes, you can use parts of this in a commercial add-on.
